In [1]:
import numpy as np

In [20]:
def Gaussseidelmethod(A,b,x0,e,nmax):
    n = A.shape[0]
    xk = np.zeros(n)
    for k in range(1,nmax):
        #xk[0] = -sum([A[0,j]/A[0,0]*x0[j] for j in range(1,n)]) + b[0]/A[0,0]
        for i in range(n):
            xk[i] = -sum([A[i,j]/A[i,i]*xk[j] for j in range(n) if j<i]) -sum([A[i,j]/A[i,i]*x0[j] for j in range(n) if j>i]) + b[i]/A[i,i]
        print(xk)
        print(x0)
        if sum((xk-x0)**2)**(1/2) <= e:
            print("{}th convergence".format(k))
            return xk, x0
        x0 = xk.copy()
    print(x0,xk,"moham?")
    return
    

In [22]:
A = np.matrix([[11,2,3],[4,51,6],[7,8,11]])
b = np.ones(3)
x0 = np.ones(3)

In [23]:
Gaussseidelmethod(A,b,x0,0.001,100)

[-0.36363636 -0.06951872  0.37287312]
[1. 1. 1.]
[ 0.00185619 -0.02440517  0.10747709]
[-0.36363636 -0.06951872  0.37287312]
[0.06603446 0.00178431 0.04758948]
[ 0.00185619 -0.02440517  0.10747709]
[0.07760572 0.00792236 0.03576192]
[0.06603446 0.00178431 0.04758948]
[0.07971541 0.00914837 0.03352774]
[0.07760572 0.00792236 0.03576192]
[0.08010182 0.00938091 0.03311273]
[0.07971541 0.00914837 0.03352774]
6th convergence


(array([0.08010182, 0.00938091, 0.03311273]),
 array([0.07971541, 0.00914837, 0.03352774]))

In [24]:
A.dot(Gaussseidelmethod(A,b,x0,0.001,100)[0])

[-0.36363636 -0.06951872  0.37287312]
[1. 1. 1.]
[ 0.00185619 -0.02440517  0.10747709]
[-0.36363636 -0.06951872  0.37287312]
[0.06603446 0.00178431 0.04758948]
[ 0.00185619 -0.02440517  0.10747709]
[0.07760572 0.00792236 0.03576192]
[0.06603446 0.00178431 0.04758948]
[0.07971541 0.00914837 0.03352774]
[0.07760572 0.00792236 0.03576192]
[0.08010182 0.00938091 0.03311273]
[0.07971541 0.00914837 0.03352774]
6th convergence


matrix([[0.99922003, 0.99750991, 1.        ]])