In [2]:
import numpy as np

In [5]:
def Jacobimethod(A,b,x0,e,nmax):
    n = A.shape[0]
    xk = np.zeros(n)
    for k in range(nmax):
        for i in range(n):
            xk[i] = -sum([A[i,j]/A[i,i]*x0[j] for j in range(n) if j != i]) + b[i]/A[i,i]
        print(xk)
        print(x0)
        if sum((xk-x0)**2)**(1/2) <= e:
            print("{}th convergence".format(k))
            return xk,x0
        x0 = xk.copy()
    print(x0,xk,"not convergence")
    return


In [6]:
A = np.matrix([[11,2,3],[4,51,6],[7,8,11]])

In [7]:
x0=np.array([1,1,1])

In [8]:
np.diag(np.diag(A))

array([[11,  0,  0],
       [ 0, 51,  0],
       [ 0,  0, 11]])

In [9]:
b = np.ones(3)

In [10]:
Jacobimethod(A,b,x0,0.001,100)

[-0.36363636 -0.17647059 -1.27272727]
[1 1 1]
[0.47010209 0.19786096 0.4506563 ]
[-0.36363636 -0.17647059 -1.27272727]
[-0.06797189 -0.0702813  -0.35214567]
[0.47010209 0.19786096 0.4506563 ]
[0.19972724 0.06636787 0.1852776 ]
[-0.06797189 -0.0702813  -0.35214567]
[ 0.02831195 -0.0178544  -0.0844576 ]
[0.19972724 0.06636787 0.1852776 ]
[0.11718924 0.02732349 0.08587742]
[ 0.02831195 -0.0178544  -0.0844576 ]
[ 0.06252007  0.0003133  -0.00353751]
[0.11718924 0.02732349 0.08587742]
[0.0918169  0.01512049 0.05089573]
[ 0.06252007  0.0003133  -0.00353751]
[0.07427926 0.00641878 0.02148344]
[0.0918169  0.01512049 0.05089573]
[0.08388292 0.01125456 0.03897227]
[0.07427926 0.00641878 0.02148344]
[0.07823401 0.00844382 0.02934392]
[0.08388292 0.01125456 0.03897227]
[0.08137096 0.01001962 0.03498285]
[0.07823401 0.00844382 0.02934392]
[0.07954656 0.00911018 0.03184057]
[0.08137096 0.01001962 0.03498285]
[0.0805689  0.00962295 0.03366297]
[0.07954656 0.00911018 0.03184057]
[0.07997865 0.00932836 

(array([0.08031135, 0.00949507, 0.03322932]),
 array([0.07997865, 0.00932836, 0.03263946]))

In [13]:
A.dot(Jacobimethod(A,b,x0,0.001,100)[0])

[-0.36363636 -0.17647059 -1.27272727]
[1 1 1]
[0.47010209 0.19786096 0.4506563 ]
[-0.36363636 -0.17647059 -1.27272727]
[-0.06797189 -0.0702813  -0.35214567]
[0.47010209 0.19786096 0.4506563 ]
[0.19972724 0.06636787 0.1852776 ]
[-0.06797189 -0.0702813  -0.35214567]
[ 0.02831195 -0.0178544  -0.0844576 ]
[0.19972724 0.06636787 0.1852776 ]
[0.11718924 0.02732349 0.08587742]
[ 0.02831195 -0.0178544  -0.0844576 ]
[ 0.06252007  0.0003133  -0.00353751]
[0.11718924 0.02732349 0.08587742]
[0.0918169  0.01512049 0.05089573]
[ 0.06252007  0.0003133  -0.00353751]
[0.07427926 0.00641878 0.02148344]
[0.0918169  0.01512049 0.05089573]
[0.08388292 0.01125456 0.03897227]
[0.07427926 0.00641878 0.02148344]
[0.07823401 0.00844382 0.02934392]
[0.08388292 0.01125456 0.03897227]
[0.08137096 0.01001962 0.03498285]
[0.07823401 0.00844382 0.02934392]
[0.07954656 0.00911018 0.03184057]
[0.08137096 0.01001962 0.03498285]
[0.0805689  0.00962295 0.03366297]
[0.07954656 0.00911018 0.03184057]
[0.07997865 0.00932836 

matrix([[1.00210297, 1.00486991, 1.00366253]])